# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git ruby brew rvm nvm)

source $ZSH/oh-my-zsh.sh
export RVM_PATH="$HOME/.rvm"      # Path to RVM
export GEM_HOME="$RVM_PATH/gems"  # Gems

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export EDITOR="subl -w" # Sublime Text Editor

# Android Emulator
export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export ANDROID_HOME="$ANDROID_SDK_ROOT"
export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
export PATH="$PATH:$ANDROID_SDK_ROOT/emulator"
export PATH="$PATH:$ANDROID_SDK_ROOT/tools"
export PATH="$PATH:$ANDROID_SDK_ROOT/platform-tools"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$GEM_HOME/bin:$PATH"

#### Docker Stuff ###################################

# Find a docker-container, and attach to it
# To detach, by default this is Ctrl-P/Ctrl-Q
# but most people think that Control-C should do it, so we set that
# Ref: https://docs.docker.com/engine/reference/commandline/attach
#
# Note: in order to attach to a container, you must have it started
# with docker-compose settings:
# app:
#   tty: true
#   stdin_open: true
function docker-compose-attach() {
  docker attach $(docker-compose ps -q $1) --detach-keys="ctrl-c";
}

alias dockerc='docker-compose'
alias dockerc-attach='docker-compose-attach'
alias dockerc-attach='docker-compose-attach'

# Helpful Aliases
alias whatismyip="dig +short myip.opendns.com @resolver1.opendns.com"
